name: Build PR Documentation

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Echo
        run: |
          echo ${{ env.GITHUB_EVENT_NAME }}
          echo ${{ toJSON(github.event) }}
          echo ${{ toJSON(github) }}
          echo ${{ toJSON(github.event.number) }}
          echo ${{ toJSON(github.event.pull_request) }}
  build:
    uses: lysandrejik/doc-builder/.github/workflows/build_pr_documentation.yml@lysandrejik-workflow
    with:
      commit_sha: ${{ github.event.pull_request.head.sha }}
      pr_number: ${{ github.event.number }}
      package: huggingface_hub