name: Contrib tests

on:
  workflow_dispatch:
  push:
    branches:
      - ci_contrib_*
      - 1190-rfc-add-contrib-test-suite

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        contrib: [
          "timm",
        ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # Install pip
      - name: Install pip
        run: pip install --upgrade pip

      # Install downstream library
      - name: Install ${{ matrix.contrib }}
        run: pip install -r contrib/reqs_${{ matrix.contrib }}.txt

      # Install huggingface_hub as last from source code
      - name: Install `huggingface_hub`
        run: |
          pip uninstall huggingface_hub
          pip install .

      # Run tests
      - name: Run tests
        run: pytest contrib/${{ matrix.contrib }}
